### ISSUE TITLE
Hard coded regions into the inventory

### ISSUE THREAD

**Issue by nirekin** [lagoon-platform/aws-provider#14]
To check: it seems than the inventory is based on an hard coded regions list...

In `lagoon.aws_ec2.yml` : 

```yaml
regions:
- eu-west-1
- eu-west-2
- eu-central-1 
```
Is it's really the case this is not a viable solution, because we can not be sure that all the environments will be built in those sole regions.

**Comment by adrienlauer** [comment]
Fixed with dynamic inventories
